baseURL = "https://suksest.github.io/"
languageCode = "en-us"
title = "Sukma's tech blog"
theme = "dream"

[params]
  author = "Sukma Setyaji"
  motto = "you'll be remembered"
  headerTitle = "Sukma's tech blog"
  avatar = "/img/avatar.jpg"
  favicon = "/img/sysadmin.png"

  email = "suksest@gmail.com"
  github = "suksest"
  linkedin = "sukma-setyaji"
  codepen = ""
  stackoverflow = ""
